watermarker:
  hash_value: 737800
  green_list_size: 0.25
  hardness: 2
  z_threshold: 4

sampler:
  top_k: 10
  frequency_penalty: 1.1
  presence_penalty: 1.2

model:
  model_name: "openai-community/gpt2-large"
  num_output_tokens: 100

general:
  input_directory: "input"
  input_filename: "test.txt"
  output_directory: "output"