watermarker:
  hash_value: 737800
  green_list_size: 0.25
  hardness: 2
  z_threshold: 4

sampler:
  type: "top_p"
  top_k: 15
  top_p: .9
  frequency_penalty: 1.0
  presence_penalty: 1.0

model:
  model_name: "openai-community/gpt2-xl"
  num_output_tokens: 150

general:
  input_directory: "input"
  input_filename: "input.txt"
  output_directory: "output"
  output_filename: "output.txt"